!
version 12.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R1
!
boot-start-marker
boot-end-marker
!
!
no aaa new-model
no ip icmp rate-limit unreachable
ip cef
ip tcp synwait-time 5
!
!
!
!
no ip domain lookup
ip domain name github.com
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
!
!
!
!
!
username chihyung privilege 15 secret 5 $1$W3bN$Qr6Gc461.OkUt7mIBlMFV/
!
!
!
!
!
!
!
interface Loopback0
 ip address 1.1.1.1 255.255.255.128
!
interface FastEthernet0/0
 no ip address
 shutdown
 duplex half
!
interface Ethernet1/0
 ip address 12.12.12.1 255.255.255.252
 duplex half
!
interface Ethernet1/1
 ip address 21.21.21.1 255.255.255.252
 duplex half
!
interface Ethernet1/2
 no ip address
 shutdown
 duplex half
!
interface Ethernet1/3
 no ip address
 shutdown
 duplex half
!
interface Ethernet1/4
 no ip address
 shutdown
 duplex half
!
interface Ethernet1/5
 no ip address
 shutdown
 duplex half
!
interface Ethernet1/6
 no ip address
 shutdown
 duplex half
!
interface Ethernet1/7
 ip address 192.168.122.10 255.255.255.0
 duplex half
!
router bgp 12121
 bgp router-id 1.1.1.1
 bgp log-neighbor-changes
 neighbor 12.12.12.2 remote-as 21212
 neighbor 21.21.21.2 remote-as 21212
 maximum-paths 2
 !
 address-family ipv4
 neighbor 12.12.12.2 activate
 neighbor 21.21.21.2 activate
 maximum-paths 2
 no auto-summary
 no synchronization
 network 1.1.1.0 mask 255.255.255.128
 exit-address-family
 !
 address-family nsap
 maximum-paths 2
 no synchronization
 exit-address-family
!
no ip http server
no ip http secure-server
!
!
!
logging alarm informational
no cdp log mismatch duplex
!
!
!
!
!
!
control-plane
!
!
!
!
!
!
gatekeeper
 shutdown
!
!
line con 0
 exec-timeout 0 0
 privilege level 15
 logging synchronous
 stopbits 1
line aux 0
 exec-timeout 0 0
 privilege level 15
 logging synchronous
 stopbits 1
line vty 0 4
 login local
 transport input all
!
!
end

